DROP DATABASE IF EXISTS Paises2025;
CREATE DATABASE Paises2025;
USE Paises2025;
DROP TABLE IF EXISTS `PaisesContinenteCodigo`;
CREATE TABLE `PaisesContinenteCodigo` (
  `ID` INTEGER,
  `nome_pais` TEXT,
  `continente` TEXT,
  `codigo_pais` TEXT
);


INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (1, 'Aruba', 'North America', 'ABW');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (2, 'Afghanistan', 'Asia', 'AFG');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (3, 'Angola', 'Africa', 'AGO');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (4, 'Anguilla', 'North America', 'AIA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (5, 'Albania', 'Europe', 'ALB');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (6, 'Andorra', 'Europe', 'AND');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (7, 'Netherlands Antilles', 'North America', 'ANT');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (8, 'United Arab Emirates', 'Asia', 'ARE');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (9, 'Argentina', 'South America', 'ARG');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (10, 'Armenia', 'Asia', 'ARM');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (11, 'American Samoa', 'Oceania', 'ASM');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (12, 'Antarctica', 'Antarctica', 'ATA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (13, 'French Southern territories', 'Antarctica', 'ATF');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (14, 'Antigua and Barbuda', 'North America', 'ATG');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (15, 'Australia', 'Oceania', 'AUS');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (16, 'Austria', 'Europe', 'AUT');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (17, 'Azerbaijan', 'Asia', 'AZE');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (18, 'Burundi', 'Africa', 'BDI');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (19, 'Belgium', 'Europe', 'BEL');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (20, 'Benin', 'Africa', 'BEN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (21, 'Burkina Faso', 'Africa', 'BFA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (22, 'Bangladesh', 'Asia', 'BGD');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (23, 'Bulgaria', 'Europe', 'BGR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (24, 'Bahrain', 'Asia', 'BHR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (25, 'Bahamas', 'North America', 'BHS');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (26, 'Bosnia and Herzegovina', 'Europe', 'BIH');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (27, 'Belarus', 'Europe', 'BLR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (28, 'Belize', 'North America', 'BLZ');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (29, 'Bermuda', 'North America', 'BMU');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (30, 'Bolivia', 'South America', 'BOL');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (31, 'Brazil', 'South America', 'BRA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (32, 'Barbados', 'North America', 'BRB');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (33, 'Brunei', 'Asia', 'BRN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (34, 'Bhutan', 'Asia', 'BTN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (35, 'Bouvet Island', 'Antarctica', 'BVT');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (36, 'Botswana', 'Africa', 'BWA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (37, 'Central African Republic', 'Africa', 'CAF');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (38, 'Canada', 'North America', 'CAN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (39, 'Cocos (Keeling) Islands', 'Oceania', 'CCK');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (40, 'Switzerland', 'Europe', 'CHE');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (41, 'Chile', 'South America', 'CHL');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (42, 'China', 'Asia', 'CHN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (43, 'Côte d’Ivoire', 'Africa', 'CIV');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (44, 'Cameroon', 'Africa', 'CMR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (45, 'Congo, The Democratic Republic of the', 'Africa', 'COD');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (46, 'Congo', 'Africa', 'COG');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (47, 'Cook Islands', 'Oceania', 'COK');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (48, 'Colombia', 'South America', 'COL');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (49, 'Comoros', 'Africa', 'COM');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (50, 'Cape Verde', 'Africa', 'CPV');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (51, 'Costa Rica', 'North America', 'CRI');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (52, 'Cuba', 'North America', 'CUB');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (53, 'Christmas Island', 'Oceania', 'CXR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (54, 'Cayman Islands', 'North America', 'CYM');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (55, 'Cyprus', 'Asia', 'CYP');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (56, 'Czech Republic', 'Europe', 'CZE');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (57, 'Germany', 'Europe', 'DEU');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (58, 'Djibouti', 'Africa', 'DJI');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (59, 'Dominica', 'North America', 'DMA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (60, 'Denmark', 'Europe', 'DNK');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (61, 'Dominican Republic', 'North America', 'DOM');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (62, 'Algeria', 'Africa', 'DZA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (63, 'Ecuador', 'South America', 'ECU');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (64, 'Egypt', 'Africa', 'EGY');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (65, 'Eritrea', 'Africa', 'ERI');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (66, 'Western Sahara', 'Africa', 'ESH');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (67, 'Spain', 'Europe', 'ESP');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (68, 'Estonia', 'Europe', 'EST');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (69, 'Ethiopia', 'Africa', 'ETH');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (70, 'Finland', 'Europe', 'FIN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (71, 'Fiji Islands', 'Oceania', 'FJI');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (72, 'Falkland Islands', 'South America', 'FLK');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (73, 'France', 'Europe', 'FRA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (74, 'Faroe Islands', 'Europe', 'FRO');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (75, 'Micronesia  Federated States of ', 'Oceania', 'FSM');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (76, 'Gabon', 'Africa', 'GAB');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (77, 'United Kingdom', 'Europe', 'GBR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (78, 'Georgia', 'Asia', 'GEO');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (79, 'Ghana', 'Africa', 'GHA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (80, 'Gibraltar', 'Europe', 'GIB');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (81, 'Guinea', 'Africa', 'GIN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (82, 'Guadeloupe', 'North America', 'GLP');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (83, 'Gambia', 'Africa', 'GMB');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (84, 'Guinea-Bissau', 'Africa', 'GNB');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (85, 'Equatorial Guinea', 'Africa', 'GNQ');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (86, 'Greece', 'Europe', 'GRC');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (87, 'Grenada', 'North America', 'GRD');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (88, 'Greenland', 'North America', 'GRL');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (89, 'Guatemala', 'North America', 'GTM');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (90, 'French Guiana', 'South America', 'GUF');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (91, 'Guam', 'Oceania', 'GUM');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (92, 'Guyana', 'South America', 'GUY');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (93, 'Hong Kong', 'Asia', 'HKG');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (94, 'Heard Island and McDonald Islands', 'Antarctica', 'HMD');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (95, 'Honduras', 'North America', 'HND');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (96, 'Croatia', 'Europe', 'HRV');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (97, 'Haiti', 'North America', 'HTI');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (98, 'Hungary', 'Europe', 'HUN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (99, 'Indonesia', 'Asia', 'IDN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (100, 'India', 'Asia', 'IND');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (101, 'British Indian Ocean Territory', 'Africa', 'IOT');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (102, 'Ireland', 'Europe', 'IRL');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (103, 'Iran', 'Asia', 'IRN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (104, 'Iraq', 'Asia', 'IRQ');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (105, 'Iceland', 'Europe', 'ISL');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (106, 'Israel', 'Asia', 'ISR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (107, 'Italy', 'Europe', 'ITA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (108, 'Jamaica', 'North America', 'JAM');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (109, 'Jordan', 'Asia', 'JOR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (110, 'Japan', 'Asia', 'JPN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (111, 'Kazakstan', 'Asia', 'KAZ');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (112, 'Kenya', 'Africa', 'KEN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (113, 'Kyrgyzstan', 'Asia', 'KGZ');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (114, 'Cambodia', 'Asia', 'KHM');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (115, 'Kiribati', 'Oceania', 'KIR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (116, 'Saint Kitts and Nevis', 'North America', 'KNA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (117, 'South Korea', 'Asia', 'KOR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (118, 'Kuwait', 'Asia', 'KWT');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (119, 'Laos', 'Asia', 'LAO');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (120, 'Lebanon', 'Asia', 'LBN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (121, 'Liberia', 'Africa', 'LBR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (122, 'Libya', 'Africa', 'LBY');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (123, 'Saint Lucia', 'North America', 'LCA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (124, 'Liechtenstein', 'Europe', 'LIE');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (125, 'Sri Lanka', 'Asia', 'LKA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (126, 'Lesotho', 'Africa', 'LSO');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (127, 'Lithuania', 'Europe', 'LTU');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (128, 'Luxembourg', 'Europe', 'LUX');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (129, 'Latvia', 'Europe', 'LVA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (130, 'Macao', 'Asia', 'MAC');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (131, 'Morocco', 'Africa', 'MAR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (132, 'Monaco', 'Europe', 'MCO');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (133, 'Moldova', 'Europe', 'MDA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (134, 'Madagascar', 'Africa', 'MDG');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (135, 'Maldives', 'Asia', 'MDV');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (136, 'Mexico', 'North America', 'MEX');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (137, 'Marshall Islands', 'Oceania', 'MHL');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (138, 'Macedonia', 'Europe', 'MKD');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (139, 'Mali', 'Africa', 'MLI');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (140, 'Malta', 'Europe', 'MLT');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (141, 'Myanmar', 'Asia', 'MMR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (142, 'Mongolia', 'Asia', 'MNG');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (143, 'Northern Mariana Islands', 'Oceania', 'MNP');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (144, 'Mozambique', 'Africa', 'MOZ');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (145, 'Mauritania', 'Africa', 'MRT');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (146, 'Montserrat', 'North America', 'MSR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (147, 'Martinique', 'North America', 'MTQ');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (148, 'Mauritius', 'Africa', 'MUS');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (149, 'Malawi', 'Africa', 'MWI');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (150, 'Malaysia', 'Asia', 'MYS');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (151, 'Mayotte', 'Africa', 'MYT');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (152, 'Namibia', 'Africa', 'NAM');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (153, 'New Caledonia', 'Oceania', 'NCL');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (154, 'Niger', 'Africa', 'NER');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (155, 'Norfolk Island', 'Oceania', 'NFK');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (156, 'Nigeria', 'Africa', 'NGA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (157, 'Nicaragua', 'North America', 'NIC');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (158, 'Niue', 'Oceania', 'NIU');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (159, 'Netherlands', 'Europe', 'NLD');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (160, 'Norway', 'Europe', 'NOR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (161, 'Nepal', 'Asia', 'NPL');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (162, 'Nauru', 'Oceania', 'NRU');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (163, 'New Zealand', 'Oceania', 'NZL');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (164, 'Oman', 'Asia', 'OMN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (165, 'Pakistan', 'Asia', 'PAK');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (166, 'Panama', 'North America', 'PAN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (167, 'Pitcairn', 'Oceania', 'PCN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (168, 'Peru', 'South America', 'PER');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (169, 'Philippines', 'Asia', 'PHL');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (170, 'Palau', 'Oceania', 'PLW');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (171, 'Papua New Guinea', 'Oceania', 'PNG');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (172, 'Poland', 'Europe', 'POL');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (173, 'Puerto Rico', 'North America', 'PRI');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (174, 'North Korea', 'Asia', 'PRK');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (175, 'Portugal', 'Europe', 'PRT');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (176, 'Paraguay', 'South America', 'PRY');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (177, 'Palestine', 'Asia', 'PSE');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (178, 'French Polynesia', 'Oceania', 'PYF');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (179, 'Qatar', 'Asia', 'QAT');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (180, 'Réunion', 'Africa', 'REU');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (181, 'Romania', 'Europe', 'ROM');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (182, 'Russian Federation', 'Europe', 'RUS');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (183, 'Rwanda', 'Africa', 'RWA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (184, 'Saudi Arabia', 'Asia', 'SAU');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (185, 'Sudan', 'Africa', 'SDN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (186, 'Senegal', 'Africa', 'SEN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (187, 'Singapore', 'Asia', 'SGP');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (188, 'South Georgia and the South Sandwich Islands', 'Antarctica', 'SGS');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (189, 'Saint Helena', 'Africa', 'SHN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (190, 'Svalbard and Jan Mayen', 'Europe', 'SJM');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (191, 'Solomon Islands', 'Oceania', 'SLB');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (192, 'Sierra Leone', 'Africa', 'SLE');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (193, 'El Salvador', 'North America', 'SLV');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (194, 'San Marino', 'Europe', 'SMR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (195, 'Somalia', 'Africa', 'SOM');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (196, 'Saint Pierre and Miquelon', 'North America', 'SPM');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (197, 'Sao Tome and Principe', 'Africa', 'STP');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (198, 'Suriname', 'South America', 'SUR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (199, 'Slovakia', 'Europe', 'SVK');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (200, 'Slovenia', 'Europe', 'SVN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (201, 'Sweden', 'Europe', 'SWE');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (202, 'Swaziland', 'Africa', 'SWZ');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (203, 'Seychelles', 'Africa', 'SYC');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (204, 'Syria', 'Asia', 'SYR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (205, 'Turks and Caicos Islands', 'North America', 'TCA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (206, 'Chad', 'Africa', 'TCD');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (207, 'Togo', 'Africa', 'TGO');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (208, 'Thailand', 'Asia', 'THA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (209, 'Tajikistan', 'Asia', 'TJK');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (210, 'Tokelau', 'Oceania', 'TKL');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (211, 'Turkmenistan', 'Asia', 'TKM');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (212, 'East Timor', 'Asia', 'TMP');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (213, 'Tonga', 'Oceania', 'TON');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (214, 'Trinidad and Tobago', 'North America', 'TTO');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (215, 'Tunisia', 'Africa', 'TUN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (216, 'Turkey', 'Asia', 'TUR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (217, 'Tuvalu', 'Oceania', 'TUV');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (218, 'Taiwan', 'Asia', 'TWN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (219, 'Tanzania', 'Africa', 'TZA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (220, 'Uganda', 'Africa', 'UGA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (221, 'Ukraine', 'Europe', 'UKR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (222, 'United States Minor Outlying Islands', 'Oceania', 'UMI');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (223, 'Uruguay', 'South America', 'URY');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (224, 'United States', 'North America', 'USA');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (225, 'Uzbekistan', 'Asia', 'UZB');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (226, 'Holy See (Vatican City State)', 'Europe', 'VAT');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (227, 'Saint Vincent and the Grenadines', 'North America', 'VCT');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (228, 'Venezuela', 'South America', 'VEN');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (229, 'Virgin Islands  British', 'North America', 'VGB');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (230, 'Virgin Islands  U.S.', 'North America', 'VIR');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (231, 'Vietnam', 'Asia', 'VNM');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (232, 'Vanuatu', 'Oceania', 'VUT');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (233, 'Wallis and Futuna', 'Oceania', 'WLF');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (234, 'Samoa', 'Oceania', 'WSM');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (235, 'Yemen', 'Asia', 'YEM');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (236, 'Yugoslavia', 'Europe', 'YUG');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (237, 'South Africa', 'Africa', 'ZAF');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (238, 'Zambia', 'Africa', 'ZMB');
INSERT INTO `PaisesContinenteCodigo` (`ID`, `nome_pais`, `continente`, `codigo_pais`) VALUES (239, 'Zimbabwe', 'Africa', 'ZWE');
DROP TABLE IF EXISTS `DadosPaises2`;
CREATE TABLE `DadosPaises2` (
  `codigo_pais` TEXT,
  `capital` TEXT,
  `populacao` REAL,
  `idh` REAL,
  `pib_usd` REAL,
  `pib_per_capita_usd` REAL
);

INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ABW', 'Oranjestad', 107000.0, 0.907, 3200000000.0, 29907.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('AFG', 'Kabul', 42500000.0, 0.478, 15000000000.0, 353.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('AGO', 'Luanda', 36680000.0, 0.586, 120000000000.0, 3274.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('AIA', 'The Valley', 16000.0, NULL, 310000000.0, 19375.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ALB', 'Tirana', 2838000.0, 0.796, 23000000000.0, 8106.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('AND', 'Andorra la Vella', 80000.0, 0.858, 3200000000.0, 40000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ANT', 'Willemstad', 227000.0, NULL, NULL, NULL);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ARE', 'Abu Dhabi', 9516000.0, 0.911, 510000000000.0, 53400.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ARG', 'Buenos Aires', 45700000.0, 0.842, 640000000000.0, 14000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ARM', 'Yerevan', 2963000.0, 0.759, 21000000000.0, 7090.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ASM', 'Pago Pago', 49000.0, NULL, 640000000.0, 13061.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ATA', NULL, 0.0, NULL, NULL, NULL);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ATF', 'Port-aux-Français', 0.0, NULL, NULL, NULL);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ATG', 'St. John''s', 94000.0, 0.778, 1800000000.0, 19149.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('AUS', 'Canberra', 26700000.0, 0.951, 1700000000000.0, 64200.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('AUT', 'Vienna', 9040000.0, 0.921, 500000000000.0, 55200.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('AZE', 'Baku', 10400000.0, 0.745, 81000000000.0, 7788.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('BDI', 'Gitega', 13670000.0, 0.426, 3700000000.0, 270.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('BEL', 'Brussels', 11630000.0, 0.937, 600000000000.0, 51500.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('BEN', 'Porto-Novo', 13630000.0, 0.545, 21000000000.0, 1540.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('BFA', 'Ouagadougou', 22800000.0, 0.449, 22000000000.0, 965.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('BGD', 'Dhaka', 172900000.0, 0.661, 450000000000.0, 2596.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('BGR', 'Sofia', 6698000.0, 0.795, 92000000000.0, 13741.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('BHR', 'Manama', 1480000.0, 0.875, 84000000000.0, 56700.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('BHS', 'Nassau', 412000.0, 0.812, 13000000000.0, 31500.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('BIH', 'Sarajevo', 3240000.0, 0.79, 27000000000.0, 8320.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('BLR', 'Minsk', 9498000.0, 0.808, 75000000000.0, 7895.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('BLZ', 'Belmopan', 441000.0, 0.716, 2700000000.0, 6123.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('BMU', 'Hamilton', 64000.0, NULL, 7100000000.0, 111000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('BOL', 'Sucre', 12400000.0, 0.693, 46000000000.0, 3700.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('BRA', 'Brasília', 214300000.0, 0.76, 2100000000000.0, 10100.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('BRB', 'Bridgetown', 281000.0, 0.814, 5500000000.0, 19570.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('BRN', 'Bandar Seri Begawan', 454000.0, 0.829, 17000000000.0, 37400.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('BTN', 'Thimphu', 787000.0, 0.666, 2700000000.0, 3430.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('BVT', NULL, 0.0, NULL, NULL, NULL);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('BWA', 'Gaborone', 2670000.0, 0.735, 21000000000.0, 7860.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('CAF', 'Bangui', 5630000.0, 0.404, 2500000000.0, 445.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('CAN', 'Ottawa', 39140000.0, 0.936, 2100000000000.0, 53500.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('CCK', 'West Island', 600.0, NULL, NULL, NULL);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('CHE', 'Bern', 8800000.0, 0.962, 910000000000.0, 104000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('CHL', 'Santiago', 19600000.0, 0.855, 350000000000.0, 17870.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('CHN', 'Beijing', 1426000000.0, 0.788, 17700000000000.0, 12400.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('CIV', 'Yamoussoukro', 28800000.0, 0.55, 72000000000.0, 2500.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('CMR', 'Yaoundé', 29200000.0, 0.581, 44000000000.0, 1510.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('COD', 'Kinshasa', 102300000.0, 0.479, 65000000000.0, 635.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('COG', 'Brazzaville', 6000000.0, 0.571, 16000000000.0, 2660.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('COK', 'Avarua', 17000.0, NULL, 320000000.0, 18823.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('COL', 'Bogotá', 51900000.0, 0.752, 360000000000.0, 6900.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('COM', 'Moroni', 852000.0, 0.558, 1300000000.0, 1526.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('CPV', 'Praia', 598000.0, 0.665, 2100000000.0, 3510.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('CRI', 'San José', 5180000.0, 0.809, 74000000000.0, 14300.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('CUB', 'Havana', 11300000.0, 0.764, 110000000000.0, 9700.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('CXR', 'Flying Fish Cove', 1800.0, NULL, NULL, NULL);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('CYM', 'George Town', 69000.0, NULL, 6000000000.0, 87000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('CYP', 'Nicosia', 1250000.0, 0.896, 37000000000.0, 29600.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('CZE', 'Prague', 10800000.0, 0.899, 320000000000.0, 29700.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('DEU', 'Berlin', 83200000.0, 0.942, 4500000000000.0, 54100.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('DJI', 'Djibouti', 1120000.0, 0.549, 3700000000.0, 3304.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('DMA', 'Roseau', 74000.0, 0.742, 600000000.0, 8108.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('DNK', 'Copenhagen', 5900000.0, 0.94, 400000000000.0, 67800.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('DOM', 'Santo Domingo', 11300000.0, 0.767, 114000000000.0, 10100.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('DZA', 'Algiers', 45600000.0, 0.745, 206000000000.0, 4520.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ECU', 'Quito', 18000000.0, 0.759, 115000000000.0, 6390.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('EGY', 'Cairo', 112700000.0, 0.731, 404000000000.0, 3585.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ERI', 'Asmara', 3600000.0, 0.501, 2300000000.0, 639.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ESH', 'Laayoune', 500000.0, NULL, NULL, NULL);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ESP', 'Madrid', 47700000.0, 0.905, 1600000000000.0, 33500.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('EST', 'Tallinn', 1330000.0, 0.892, 42000000000.0, 31600.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ETH', 'Addis Ababa', 126500000.0, 0.498, 156000000000.0, 1232.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('FIN', 'Helsinki', 5540000.0, 0.94, 300000000000.0, 54100.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('FJI', 'Suva', 936000.0, 0.744, 5500000000.0, 5877.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('FLK', 'Stanley', 3500.0, NULL, 75000000.0, 21429.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('FRA', 'Paris', 68300000.0, 0.903, 3000000000000.0, 44000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('FRO', 'Tórshavn', 54000.0, NULL, 3200000000.0, 59259.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('FSM', 'Palikir', 116000.0, 0.62, 400000000.0, 3448.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('GAB', 'Libreville', 2400000.0, 0.706, 22000000000.0, 9167.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('GBR', 'London', 67800000.0, 0.929, 3300000000000.0, 48600.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('GEO', 'Tbilisi', 3720000.0, 0.802, 24000000000.0, 6450.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('GHA', 'Accra', 34100000.0, 0.632, 77000000000.0, 2260.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('GIB', 'Gibraltar', 34000.0, NULL, 2400000000.0, 70588.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('GIN', 'Conakry', 14300000.0, 0.477, 19000000000.0, 1329.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('GLP', 'Basse-Terre', 400000.0, NULL, 9500000000.0, 23750.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('GMB', 'Banjul', 2700000.0, 0.496, 2300000000.0, 852.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('GNB', 'Bissau', 2200000.0, 0.483, 1700000000.0, 772.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('GNQ', 'Malabo', 1700000.0, 0.588, 13000000000.0, 7647.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('GRC', 'Athens', 10400000.0, 0.891, 240000000000.0, 23100.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('GRD', 'St. George''s', 126000.0, 0.779, 1200000000.0, 9524.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('GRL', 'Nuuk', 57000.0, NULL, 3100000000.0, 54386.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('GTM', 'Guatemala City', 18700000.0, 0.663, 97000000000.0, 5187.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('GUF', 'Cayenne', 310000.0, NULL, 4900000000.0, 15806.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('GUM', 'Hagåtña', 170000.0, NULL, 6400000000.0, 37647.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('GUY', 'Georgetown', 813000.0, 0.682, 16000000000.0, 19680.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('HKG', 'Hong Kong', 7500000.0, NULL, 400000000000.0, 53333.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('HMD', NULL, 0.0, NULL, NULL, NULL);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('HND', 'Tegucigalpa', 10600000.0, 0.621, 32000000000.0, 3018.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('HRV', 'Zagreb', 3900000.0, 0.858, 82000000000.0, 21025.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('HTI', 'Port-au-Prince', 11700000.0, 0.535, 21000000000.0, 1795.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('HUN', 'Budapest', 9700000.0, 0.848, 180000000000.0, 18557.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('IDN', 'Jakarta', 277500000.0, 0.718, 1300000000000.0, 4685.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('IND', 'New Delhi', 1428000000.0, 0.644, 3700000000000.0, 2590.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('IOT', 'Diego Garcia', 4000.0, NULL, NULL, NULL);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('IRL', 'Dublin', 5300000.0, 0.945, 520000000000.0, 98000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('IRN', 'Tehran', 89100000.0, 0.774, 410000000000.0, 4600.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('IRQ', 'Baghdad', 45500000.0, 0.685, 270000000000.0, 5934.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ISL', 'Reykjavik', 380000.0, 0.959, 30000000000.0, 78947.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ISR', 'Jerusalem', 9700000.0, 0.919, 520000000000.0, 53608.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ITA', 'Rome', 59000000.0, 0.895, 2200000000000.0, 37200.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('JAM', 'Kingston', 2820000.0, 0.726, 17000000000.0, 6037.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('JOR', 'Amman', 11200000.0, 0.72, 48000000000.0, 4286.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('JPN', 'Tokyo', 124800000.0, 0.925, 4200000000000.0, 33650.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('KAZ', 'Astana', 19600000.0, 0.811, 260000000000.0, 13265.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('KEN', 'Nairobi', 55000000.0, 0.555, 110000000000.0, 2000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('KGZ', 'Bishkek', 7000000.0, 0.697, 9500000000.0, 1357.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('KHM', 'Phnom Penh', 17000000.0, 0.594, 30000000000.0, 1764.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('KIR', 'South Tarawa', 130000.0, 0.624, 230000000.0, 1769.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('KNA', 'Basseterre', 47000.0, 0.779, 1100000000.0, 23404.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('KOR', 'Seoul', 51700000.0, 0.925, 1800000000000.0, 34700.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('KWT', 'Kuwait City', 4300000.0, 0.831, 180000000000.0, 41860.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('LAO', 'Vientiane', 7600000.0, 0.607, 18000000000.0, 2368.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('LBN', 'Beirut', 5400000.0, 0.706, 23000000000.0, 4259.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('LBR', 'Monrovia', 5400000.0, 0.477, 4700000000.0, 870.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('LBY', 'Tripoli', 7000000.0, 0.718, 45000000000.0, 6429.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('LCA', 'Castries', 180000.0, 0.747, 2200000000.0, 12222.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('LIE', 'Vaduz', 39000.0, 0.942, 7000000000.0, 179487.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('LKA', 'Sri Jayawardenepura Kotte', 22000000.0, 0.782, 91000000000.0, 4136.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('LSO', 'Maseru', 2300000.0, 0.514, 2700000000.0, 1174.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('LTU', 'Vilnius', 2800000.0, 0.891, 75000000000.0, 26786.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('LUX', 'Luxembourg', 660000.0, 0.93, 75000000000.0, 113636.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('LVA', 'Riga', 1900000.0, 0.885, 42000000000.0, 22105.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MAC', 'Macao', 680000.0, NULL, 53000000000.0, 77941.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MAR', 'Rabat', 38000000.0, 0.683, 140000000000.0, 3684.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MCO', 'Monaco', 39000.0, NULL, 8700000000.0, 223077.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MDA', 'Chisinau', 2600000.0, 0.767, 15000000000.0, 5769.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MDG', 'Antananarivo', 30400000.0, 0.533, 16000000000.0, 526.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MDV', 'Malé', 521000.0, 0.747, 6200000000.0, 11900.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MEX', 'Mexico City', 128000000.0, 0.786, 1800000000000.0, 14062.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MHL', 'Majuro', 42000.0, 0.639, 300000000.0, 7143.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MKD', 'Skopje', 2100000.0, 0.801, 14000000000.0, 6667.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MLI', 'Bamako', 23000000.0, 0.428, 19000000000.0, 826.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MLT', 'Valletta', 520000.0, 0.895, 18000000000.0, 34615.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MMR', 'Naypyidaw', 55000000.0, 0.585, 59000000000.0, 1073.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MNG', 'Ulaanbaatar', 3400000.0, 0.747, 18000000000.0, 5294.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MNP', 'Saipan', 58000.0, NULL, 1200000000.0, 20690.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MOZ', 'Maputo', 34000000.0, 0.446, 18000000000.0, 529.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MRT', 'Nouakchott', 4800000.0, 0.556, 11000000000.0, 2292.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MSR', 'Plymouth', 5000.0, NULL, 62000000.0, 12400.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MTQ', 'Fort-de-France', 370000.0, NULL, 9500000000.0, 25676.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MUS', 'Port Louis', 1300000.0, 0.802, 14000000000.0, 10769.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MWI', 'Lilongwe', 21000000.0, 0.508, 13000000000.0, 619.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MYS', 'Kuala Lumpur', 34000000.0, 0.81, 430000000000.0, 12647.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('MYT', 'Mamoudzou', 320000.0, NULL, 3200000000.0, 10000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('NAM', 'Windhoek', 2600000.0, 0.615, 13000000000.0, 5000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('NCL', 'Nouméa', 270000.0, NULL, 9500000000.0, 35185.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('NER', 'Niamey', 27000000.0, 0.4, 16000000000.0, 593.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('NFK', 'Kingston', 2200.0, NULL, NULL, NULL);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('NGA', 'Abuja', 223800000.0, 0.548, 477000000000.0, 2132.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('NIC', 'Managua', 7000000.0, 0.692, 15000000000.0, 2143.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('NIU', 'Alofi', 2000.0, NULL, 10000000.0, 5000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('NLD', 'Amsterdam', 17400000.0, 0.941, 1000000000000.0, 57471.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('NOR', 'Oslo', 5500000.0, 0.961, 550000000000.0, 100000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('NPL', 'Kathmandu', 30000000.0, 0.601, 40000000000.0, 1333.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('NRU', 'Yaren', 11000.0, NULL, 130000000.0, 11818.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('NZL', 'Wellington', 5200000.0, 0.937, 250000000000.0, 48077.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('OMN', 'Muscat', 4600000.0, 0.816, 115000000000.0, 25000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('PAK', 'Islamabad', 240000000.0, 0.54, 370000000000.0, 1542.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('PAN', 'Panama City', 4400000.0, 0.815, 76000000000.0, 17273.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('PCN', 'Adamstown', 50.0, NULL, NULL, NULL);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('PER', 'Lima', 34000000.0, 0.771, 240000000000.0, 7058.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('PHL', 'Manila', 117000000.0, 0.699, 440000000000.0, 3760.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('PLW', 'Ngerulmud', 18000.0, 0.826, 270000000.0, 15000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('PNG', 'Port Moresby', 11000000.0, 0.617, 32000000000.0, 2909.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('POL', 'Warsaw', 37000000.0, 0.88, 800000000000.0, 21622.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('PRI', 'San Juan', 3300000.0, NULL, 110000000000.0, 33333.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('PRK', 'Pyongyang', 26000000.0, NULL, 18000000000.0, 692.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('PRT', 'Lisbon', 10400000.0, 0.866, 270000000000.0, 25961.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('PRY', 'Asunción', 7100000.0, 0.728, 42000000000.0, 5915.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('PSE', 'East Jerusalem', 5400000.0, NULL, 18000000000.0, 3333.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('PYF', 'Papeete', 280000.0, NULL, 5900000000.0, 21071.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('QAT', 'Doha', 2800000.0, 0.855, 235000000000.0, 83929.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('REU', 'Saint-Denis', 970000.0, NULL, 21000000000.0, 21649.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ROM', 'Bucharest', 19000000.0, 0.821, 340000000000.0, 17895.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('RUS', 'Moscow', 144000000.0, 0.822, 2100000000000.0, 14583.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('RWA', 'Kigali', 14000000.0, 0.534, 13000000000.0, 929.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SAU', 'Riyadh', 36000000.0, 0.875, 1100000000000.0, 30556.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SDN', 'Khartoum', 48000000.0, 0.508, 34000000000.0, 708.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SEN', 'Dakar', 18000000.0, 0.528, 29000000000.0, 1611.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SGP', 'Singapore', 6000000.0, 0.939, 470000000000.0, 78333.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SGS', 'King Edward Point', 30.0, NULL, NULL, NULL);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SHN', 'Jamestown', 6000.0, NULL, 31000000.0, 5167.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SJM', 'Longyearbyen', 2900.0, NULL, NULL, NULL);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SLB', 'Honiara', 740000.0, 0.564, 1800000000.0, 2432.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SLE', 'Freetown', 8600000.0, 0.477, 4700000000.0, 547.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SLV', 'San Salvador', 6500000.0, 0.673, 32000000000.0, 4923.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SMR', 'San Marino', 34000.0, 0.961, 2200000000.0, 64706.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SOM', 'Mogadishu', 18000000.0, 0.38, 8000000000.0, 444.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SPM', 'Saint-Pierre', 6000.0, NULL, 215000000.0, 35833.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('STP', 'São Tomé', 230000.0, 0.646, 530000000.0, 2304.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SUR', 'Paramaribo', 630000.0, 0.73, 5300000000.0, 8413.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SVK', 'Bratislava', 5400000.0, 0.857, 130000000000.0, 24074.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SVN', 'Ljubljana', 2100000.0, 0.918, 67000000000.0, 31905.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SWE', 'Stockholm', 10600000.0, 0.947, 660000000000.0, 62264.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SWZ', 'Mbabane', 1200000.0, 0.611, 4700000000.0, 3917.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SYC', 'Victoria', 100000.0, 0.796, 1800000000.0, 18000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('SYR', 'Damascus', 22000000.0, NULL, 60000000000.0, 2727.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('TCA', 'Cockburn Town', 45000.0, NULL, 950000000.0, 21111.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('TCD', 'N''Djamena', 18000000.0, 0.394, 12000000000.0, 667.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('TGO', 'Lomé', 9000000.0, 0.539, 8000000000.0, 889.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('THA', 'Bangkok', 72000000.0, 0.8, 520000000000.0, 7222.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('TJK', 'Dushanbe', 10000000.0, 0.707, 10000000000.0, 1000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('TKL', 'Fakaofo', 1400.0, NULL, NULL, NULL);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('TKM', 'Ashgabat', 6500000.0, 0.721, 48000000000.0, 7385.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('TMP', 'Dili', 1400000.0, 0.626, 2500000000.0, 1786.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('TON', 'Nuku''alofa', 107000.0, 0.725, 550000000.0, 5140.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('TTO', 'Port of Spain', 1500000.0, 0.81, 30000000000.0, 20000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('TUN', 'Tunis', 12400000.0, 0.74, 49000000000.0, 3952.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('TUR', 'Ankara', 86000000.0, 0.838, 1100000000000.0, 12791.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('TUV', 'Funafuti', 12000.0, NULL, 60000000.0, 5000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('TWN', 'Taipei', 23600000.0, NULL, 790000000000.0, 33400.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('TZA', 'Dodoma', 67000000.0, 0.549, 85000000000.0, 1269.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('UGA', 'Kampala', 48000000.0, 0.544, 45000000000.0, 938.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('UKR', 'Kyiv', 37000000.0, 0.773, 150000000000.0, 4054.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('UMI', 'Johnston Atoll', 300.0, NULL, NULL, NULL);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('URY', 'Montevideo', 3500000.0, 0.809, 70000000000.0, 20000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('USA', 'Washington', 332000000.0, 0.921, 26900000000000.0, 81000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('UZB', 'Tashkent', 35000000.0, 0.727, 80000000000.0, 2286.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('VAT', 'Vatican City', 800.0, NULL, NULL, NULL);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('VCT', 'Kingstown', 110000.0, 0.723, 900000000.0, 8182.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('VEN', 'Caracas', 28000000.0, NULL, 110000000000.0, 3928.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('VGB', 'Road Town', 31000.0, NULL, 1200000000.0, 38710.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('VIR', 'Charlotte Amalie', 106000.0, NULL, 4900000000.0, 46226.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('VNM', 'Hanoi', 99000000.0, 0.703, 410000000000.0, 4141.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('VUT', 'Port Vila', 340000.0, 0.607, 1000000000.0, 2941.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('WLF', 'Mata-Utu', 11000.0, NULL, 150000000.0, 13636.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('WSM', 'Apia', 225000.0, 0.726, 900000000.0, 4000.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('YEM', 'Sana''a', 34000000.0, 0.455, 21000000000.0, 617.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('YUG', 'Belgrade', NULL, NULL, NULL, NULL);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ZAF', 'Pretoria', 60000000.0, 0.713, 400000000000.0, 6667.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ZMB', 'Lusaka', 20400000.0, 0.579, 30000000000.0, 1471.0);
INSERT INTO `DadosPaises2` (`codigo_pais`, `capital`, `populacao`, `idh`, `pib_usd`, `pib_per_capita_usd`) VALUES ('ZWE', 'Harare', 16600000.0, 0.571, 21000000000.0, 1265.0);
